SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600

BASE_ASTEROID_MIN_RADIUS = 20
BASE_ASTEROID_KINDS = 3
BASE_ASTEROID_SPAWN_RATE = 0.5 
BASE_ASTEROID_MAX_RADIUS = BASE_ASTEROID_MIN_RADIUS * BASE_ASTEROID_KINDS
BASE_ASTEROID_POINTS = 10

BASE_PLAYER_RADIUS = 20
BASE_PLAYER_TURN_SPEED = 300
BASE_PLAYER_SPEED = 200
BASE_PLAYER_SHOOT_SPEED = 500 #500
BASE_PLAYER_SHOOT_COOLDOWN = 0.3

BASE_ITEM_DROP_RADIUS = 10
BASE_POS_ITEM_DROP_CHANCE = 0.1
BASE_NEG_ITEM_DROP_CHANCE = 0.2

BASE_SHOT_RADIUS = 5

BASE_SCORE_MULTIPLIER = 1

# Music
INGAME_MUSIC_PATH = "music/space_background.mp3"
MENU_MUSIC_PATH = "music/menu_background.mp3"
NORMAL_SHOT_PATH = "music/normal_shot.mp3"
BIG_SHOT_PATH = "music/big_shot.mp3"
ASTEROID_EXPLOSION = "music/asteroid_explodes.mp3"

